// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    jornada,
    jornadaColportorIdx,
  ];
  late final Shape0 jornada = Shape0(
    source: i0.VersionedTable(
      entityName: 'jornada',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'CHECK(total_visitas >= 0)',
        'CHECK(total_ventas >= 0)',
        'CHECK(fin IS NULL OR fin >= inicio)',
      ],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index jornadaColportorIdx = i1.Index(
    'jornada_colportor_idx',
    'CREATE INDEX jornada_colportor_idx ON jornada (colportor_id, inicio)',
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get colportorId =>
      columnsByName['colportor_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get inicio =>
      columnsByName['inicio']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get fin =>
      columnsByName['fin']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get acompanianteId =>
      columnsByName['acompaniante_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get tipoAcompaniamiento =>
      columnsByName['tipo_acompaniamiento']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get totalVisitas =>
      columnsByName['total_visitas']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get totalVentas =>
      columnsByName['total_ventas']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get createdBy =>
      columnsByName['created_by']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get syncVersion =>
      columnsByName['sync_version']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_0(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'colportor_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_2(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'inicio',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_3(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'fin',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_4(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'acompaniante_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_5(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'tipo_acompaniamiento',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_6(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'total_visitas',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_7(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'total_ventas',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_8(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'created_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_9(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'updated_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_10(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'created_by',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_11(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'deleted_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_12(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'sync_version',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );

final class Schema3 extends i0.VersionedSchema {
  Schema3({required super.database}) : super(version: 3);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    jornada,
    ubicacion,
    espacio,
    jornadaColportorIdx,
    ubicacionCiudadIdx,
    espacioUbicacionIdx,
  ];
  late final Shape0 jornada = Shape0(
    source: i0.VersionedTable(
      entityName: 'jornada',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'CHECK(total_visitas >= 0)',
        'CHECK(total_ventas >= 0)',
        'CHECK(fin IS NULL OR fin >= inicio)',
      ],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 ubicacion = Shape1(
    source: i0.VersionedTable(
      entityName: 'ubicacion',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'CHECK(tipo IN (\'CASA\', \'NEGOCIO\', \'EDIFICIO\'))',
        'CHECK(lat BETWEEN -90 AND 90)',
        'CHECK(lon BETWEEN -180 AND 180)',
      ],
      columns: [
        _column_0,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 espacio = Shape2(
    source: i0.VersionedTable(
      entityName: 'espacio',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index jornadaColportorIdx = i1.Index(
    'jornada_colportor_idx',
    'CREATE INDEX jornada_colportor_idx ON jornada (colportor_id, inicio)',
  );
  final i1.Index ubicacionCiudadIdx = i1.Index(
    'ubicacion_ciudad_idx',
    'CREATE INDEX ubicacion_ciudad_idx ON ubicacion (ciudad_id, lat)',
  );
  final i1.Index espacioUbicacionIdx = i1.Index(
    'espacio_ubicacion_idx',
    'CREATE INDEX espacio_ubicacion_idx ON espacio (ubicacion_id)',
  );
}

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get tipo =>
      columnsByName['tipo']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get calle =>
      columnsByName['calle']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get numero =>
      columnsByName['numero']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get lat =>
      columnsByName['lat']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get lon =>
      columnsByName['lon']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get ciudadId =>
      columnsByName['ciudad_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get zonaId =>
      columnsByName['zona_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get createdBy =>
      columnsByName['created_by']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get syncVersion =>
      columnsByName['sync_version']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_13(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'tipo',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_14(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'calle',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_15(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'numero',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_16(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'lat',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_17(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'lon',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_18(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'ciudad_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_19(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'zona_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get ubicacionId =>
      columnsByName['ubicacion_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get numeroDepto =>
      columnsByName['numero_depto']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get piso =>
      columnsByName['piso']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get descripcion =>
      columnsByName['descripcion']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get createdBy =>
      columnsByName['created_by']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get syncVersion =>
      columnsByName['sync_version']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_20(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'ubicacion_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_21(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'numero_depto',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_22(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'piso',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_23(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'descripcion',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

final class Schema4 extends i0.VersionedSchema {
  Schema4({required super.database}) : super(version: 4);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    jornada,
    ubicacion,
    espacio,
    ubicacionParDecidido,
    jornadaColportorIdx,
    ubicacionCiudadIdx,
    espacioUbicacionIdx,
  ];
  late final Shape0 jornada = Shape0(
    source: i0.VersionedTable(
      entityName: 'jornada',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'CHECK(total_visitas >= 0)',
        'CHECK(total_ventas >= 0)',
        'CHECK(fin IS NULL OR fin >= inicio)',
      ],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 ubicacion = Shape1(
    source: i0.VersionedTable(
      entityName: 'ubicacion',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'CHECK(tipo IN (\'CASA\', \'NEGOCIO\', \'EDIFICIO\'))',
        'CHECK(lat BETWEEN -90 AND 90)',
        'CHECK(lon BETWEEN -180 AND 180)',
      ],
      columns: [
        _column_0,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 espacio = Shape2(
    source: i0.VersionedTable(
      entityName: 'espacio',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 ubicacionParDecidido = Shape3(
    source: i0.VersionedTable(
      entityName: 'ubicacion_par_decidido',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(ubicacion_a_id, ubicacion_b_id)',
        'CHECK(decision IN (\'CONSERVAR_AMBOS\', \'IGNORAR\'))',
        'CHECK(ubicacion_a_id < ubicacion_b_id)',
      ],
      columns: [_column_24, _column_25, _column_26, _column_27],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index jornadaColportorIdx = i1.Index(
    'jornada_colportor_idx',
    'CREATE INDEX jornada_colportor_idx ON jornada (colportor_id, inicio)',
  );
  final i1.Index ubicacionCiudadIdx = i1.Index(
    'ubicacion_ciudad_idx',
    'CREATE INDEX ubicacion_ciudad_idx ON ubicacion (ciudad_id, lat)',
  );
  final i1.Index espacioUbicacionIdx = i1.Index(
    'espacio_ubicacion_idx',
    'CREATE INDEX espacio_ubicacion_idx ON espacio (ubicacion_id)',
  );
}

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get ubicacionAId =>
      columnsByName['ubicacion_a_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get ubicacionBId =>
      columnsByName['ubicacion_b_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get decision =>
      columnsByName['decision']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get decididoEn =>
      columnsByName['decidido_en']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_24(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'ubicacion_a_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_25(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'ubicacion_b_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_26(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'decision',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_27(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'decidido_en',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      case 2:
        final schema = Schema3(database: database);
        final migrator = i1.Migrator(database, schema);
        await from2To3(migrator, schema);
        return 3;
      case 3:
        final schema = Schema4(database: database);
        final migrator = i1.Migrator(database, schema);
        await from3To4(migrator, schema);
        return 4;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(
    from1To2: from1To2,
    from2To3: from2To3,
    from3To4: from3To4,
  ),
);
