// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    jornada,
    jornadaColportorIdx,
  ];
  late final Shape0 jornada = Shape0(
    source: i0.VersionedTable(
      entityName: 'jornada',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'CHECK(total_visitas >= 0)',
        'CHECK(total_ventas >= 0)',
        'CHECK(fin IS NULL OR fin >= inicio)',
      ],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index jornadaColportorIdx = i1.Index(
    'jornada_colportor_idx',
    'CREATE INDEX jornada_colportor_idx ON jornada (colportor_id, inicio)',
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get colportorId =>
      columnsByName['colportor_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get inicio =>
      columnsByName['inicio']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get fin =>
      columnsByName['fin']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get acompanianteId =>
      columnsByName['acompaniante_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get tipoAcompaniamiento =>
      columnsByName['tipo_acompaniamiento']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get totalVisitas =>
      columnsByName['total_visitas']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get totalVentas =>
      columnsByName['total_ventas']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get createdBy =>
      columnsByName['created_by']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get syncVersion =>
      columnsByName['sync_version']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_0(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'colportor_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_2(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'inicio',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_3(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'fin',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_4(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'acompaniante_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_5(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'tipo_acompaniamiento',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_6(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'total_visitas',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_7(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'total_ventas',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_8(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'created_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_9(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'updated_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_10(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'created_by',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_11(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'deleted_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_12(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'sync_version',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );

final class Schema3 extends i0.VersionedSchema {
  Schema3({required super.database}) : super(version: 3);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    jornada,
    ubicacion,
    espacio,
    jornadaColportorIdx,
    ubicacionCiudadIdx,
    espacioUbicacionIdx,
  ];
  late final Shape0 jornada = Shape0(
    source: i0.VersionedTable(
      entityName: 'jornada',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'CHECK(total_visitas >= 0)',
        'CHECK(total_ventas >= 0)',
        'CHECK(fin IS NULL OR fin >= inicio)',
      ],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 ubicacion = Shape1(
    source: i0.VersionedTable(
      entityName: 'ubicacion',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'CHECK(tipo IN (\'CASA\', \'NEGOCIO\', \'EDIFICIO\'))',
        'CHECK(lat BETWEEN -90 AND 90)',
        'CHECK(lon BETWEEN -180 AND 180)',
      ],
      columns: [
        _column_0,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 espacio = Shape2(
    source: i0.VersionedTable(
      entityName: 'espacio',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index jornadaColportorIdx = i1.Index(
    'jornada_colportor_idx',
    'CREATE INDEX jornada_colportor_idx ON jornada (colportor_id, inicio)',
  );
  final i1.Index ubicacionCiudadIdx = i1.Index(
    'ubicacion_ciudad_idx',
    'CREATE INDEX ubicacion_ciudad_idx ON ubicacion (ciudad_id, lat)',
  );
  final i1.Index espacioUbicacionIdx = i1.Index(
    'espacio_ubicacion_idx',
    'CREATE INDEX espacio_ubicacion_idx ON espacio (ubicacion_id)',
  );
}

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get tipo =>
      columnsByName['tipo']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get calle =>
      columnsByName['calle']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get numero =>
      columnsByName['numero']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get lat =>
      columnsByName['lat']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get lon =>
      columnsByName['lon']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get ciudadId =>
      columnsByName['ciudad_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get zonaId =>
      columnsByName['zona_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get createdBy =>
      columnsByName['created_by']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get syncVersion =>
      columnsByName['sync_version']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_13(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'tipo',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_14(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'calle',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_15(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'numero',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_16(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'lat',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_17(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'lon',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_18(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'ciudad_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_19(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'zona_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get ubicacionId =>
      columnsByName['ubicacion_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get numeroDepto =>
      columnsByName['numero_depto']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get piso =>
      columnsByName['piso']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get descripcion =>
      columnsByName['descripcion']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get createdBy =>
      columnsByName['created_by']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get syncVersion =>
      columnsByName['sync_version']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_20(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'ubicacion_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_21(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'numero_depto',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_22(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'piso',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_23(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'descripcion',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

final class Schema4 extends i0.VersionedSchema {
  Schema4({required super.database}) : super(version: 4);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    jornada,
    ubicacion,
    espacio,
    ubicacionParDecidido,
    jornadaColportorIdx,
    ubicacionCiudadIdx,
    espacioUbicacionIdx,
  ];
  late final Shape0 jornada = Shape0(
    source: i0.VersionedTable(
      entityName: 'jornada',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'CHECK(total_visitas >= 0)',
        'CHECK(total_ventas >= 0)',
        'CHECK(fin IS NULL OR fin >= inicio)',
      ],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 ubicacion = Shape1(
    source: i0.VersionedTable(
      entityName: 'ubicacion',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'CHECK(tipo IN (\'CASA\', \'NEGOCIO\', \'EDIFICIO\'))',
        'CHECK(lat BETWEEN -90 AND 90)',
        'CHECK(lon BETWEEN -180 AND 180)',
      ],
      columns: [
        _column_0,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 espacio = Shape2(
    source: i0.VersionedTable(
      entityName: 'espacio',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 ubicacionParDecidido = Shape3(
    source: i0.VersionedTable(
      entityName: 'ubicacion_par_decidido',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(ubicacion_a_id, ubicacion_b_id)',
        'CHECK(decision IN (\'CONSERVAR_AMBOS\', \'IGNORAR\'))',
        'CHECK(ubicacion_a_id < ubicacion_b_id)',
      ],
      columns: [_column_24, _column_25, _column_26, _column_27],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index jornadaColportorIdx = i1.Index(
    'jornada_colportor_idx',
    'CREATE INDEX jornada_colportor_idx ON jornada (colportor_id, inicio)',
  );
  final i1.Index ubicacionCiudadIdx = i1.Index(
    'ubicacion_ciudad_idx',
    'CREATE INDEX ubicacion_ciudad_idx ON ubicacion (ciudad_id, lat)',
  );
  final i1.Index espacioUbicacionIdx = i1.Index(
    'espacio_ubicacion_idx',
    'CREATE INDEX espacio_ubicacion_idx ON espacio (ubicacion_id)',
  );
}

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get ubicacionAId =>
      columnsByName['ubicacion_a_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get ubicacionBId =>
      columnsByName['ubicacion_b_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get decision =>
      columnsByName['decision']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get decididoEn =>
      columnsByName['decidido_en']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_24(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'ubicacion_a_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_25(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'ubicacion_b_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_26(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'decision',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_27(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'decidido_en',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

final class Schema5 extends i0.VersionedSchema {
  Schema5({required super.database}) : super(version: 5);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    jornada,
    ubicacion,
    espacio,
    ubicacionParDecidido,
    campaniaCiudad,
    zona,
    zonaVertice,
    jornadaColportorIdx,
    ubicacionCiudadIdx,
    espacioUbicacionIdx,
    campaniaCiudadCiudadIdIdx,
    zonaCampaniaCiudadIdx,
    zonaVerticeZonaIdx,
  ];
  late final Shape0 jornada = Shape0(
    source: i0.VersionedTable(
      entityName: 'jornada',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'CHECK(total_visitas >= 0)',
        'CHECK(total_ventas >= 0)',
        'CHECK(fin IS NULL OR fin >= inicio)',
      ],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 ubicacion = Shape1(
    source: i0.VersionedTable(
      entityName: 'ubicacion',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'CHECK(tipo IN (\'CASA\', \'NEGOCIO\', \'EDIFICIO\'))',
        'CHECK(lat BETWEEN -90 AND 90)',
        'CHECK(lon BETWEEN -180 AND 180)',
      ],
      columns: [
        _column_0,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 espacio = Shape2(
    source: i0.VersionedTable(
      entityName: 'espacio',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 ubicacionParDecidido = Shape3(
    source: i0.VersionedTable(
      entityName: 'ubicacion_par_decidido',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(ubicacion_a_id, ubicacion_b_id)',
        'CHECK(decision IN (\'CONSERVAR_AMBOS\', \'IGNORAR\'))',
        'CHECK(ubicacion_a_id < ubicacion_b_id)',
      ],
      columns: [_column_24, _column_25, _column_26, _column_27],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 campaniaCiudad = Shape4(
    source: i0.VersionedTable(
      entityName: 'campania_ciudad',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_28,
        _column_18,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 zona = Shape5(
    source: i0.VersionedTable(
      entityName: 'zona',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'CHECK(tipo_forma IN (\'RADIAL\', \'ESQUINAS\'))',
        'CHECK(tipo_forma <> \'RADIAL\' OR(centro_lat IS NOT NULL AND centro_lon IS NOT NULL AND radio_m IS NOT NULL))',
        'CHECK(radio_m IS NULL OR radio_m BETWEEN 1 AND 3000)',
        'CHECK((centro_lat IS NULL OR centro_lat BETWEEN -90 AND 90)AND(centro_lon IS NULL OR centro_lon BETWEEN -180 AND 180))',
        'CHECK(color IS NULL OR color GLOB \'#[0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f]\')',
      ],
      columns: [
        _column_0,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
        _column_34,
        _column_35,
        _column_36,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 zonaVertice = Shape6(
    source: i0.VersionedTable(
      entityName: 'zona_vertice',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'CHECK(lat BETWEEN -90 AND 90)',
        'CHECK(lon BETWEEN -180 AND 180)',
      ],
      columns: [
        _column_0,
        _column_37,
        _column_38,
        _column_16,
        _column_17,
        _column_39,
        _column_40,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index jornadaColportorIdx = i1.Index(
    'jornada_colportor_idx',
    'CREATE INDEX jornada_colportor_idx ON jornada (colportor_id, inicio)',
  );
  final i1.Index ubicacionCiudadIdx = i1.Index(
    'ubicacion_ciudad_idx',
    'CREATE INDEX ubicacion_ciudad_idx ON ubicacion (ciudad_id, lat)',
  );
  final i1.Index espacioUbicacionIdx = i1.Index(
    'espacio_ubicacion_idx',
    'CREATE INDEX espacio_ubicacion_idx ON espacio (ubicacion_id)',
  );
  final i1.Index campaniaCiudadCiudadIdIdx = i1.Index(
    'campania_ciudad_ciudad_id_idx',
    'CREATE INDEX campania_ciudad_ciudad_id_idx ON campania_ciudad (ciudad_id)',
  );
  final i1.Index zonaCampaniaCiudadIdx = i1.Index(
    'zona_campania_ciudad_idx',
    'CREATE INDEX zona_campania_ciudad_idx ON zona (campania_ciudad_id)',
  );
  final i1.Index zonaVerticeZonaIdx = i1.Index(
    'zona_vertice_zona_idx',
    'CREATE INDEX zona_vertice_zona_idx ON zona_vertice (zona_id, orden)',
  );
}

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get campaniaId =>
      columnsByName['campania_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get ciudadId =>
      columnsByName['ciudad_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get createdBy =>
      columnsByName['created_by']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get syncVersion =>
      columnsByName['sync_version']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_28(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'campania_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get nombre =>
      columnsByName['nombre']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get campaniaCiudadId =>
      columnsByName['campania_ciudad_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get tipoForma =>
      columnsByName['tipo_forma']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get centroLat =>
      columnsByName['centro_lat']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get centroLon =>
      columnsByName['centro_lon']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get radioM =>
      columnsByName['radio_m']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get poligonoGeojson =>
      columnsByName['poligono_geojson']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get color =>
      columnsByName['color']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get createdBy =>
      columnsByName['created_by']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get syncVersion =>
      columnsByName['sync_version']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_29(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'nombre',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_30(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'campania_ciudad_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_31(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'tipo_forma',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_32(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'centro_lat',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_33(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'centro_lon',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_34(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'radio_m',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_35(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'poligono_geojson',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_36(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'color',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get zonaId =>
      columnsByName['zona_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get orden =>
      columnsByName['orden']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get lat =>
      columnsByName['lat']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get lon =>
      columnsByName['lon']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get calleA =>
      columnsByName['calle_a']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get calleB =>
      columnsByName['calle_b']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get createdBy =>
      columnsByName['created_by']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get syncVersion =>
      columnsByName['sync_version']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_37(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'zona_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_38(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'orden',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_39(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'calle_a',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_40(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'calle_b',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

final class Schema6 extends i0.VersionedSchema {
  Schema6({required super.database}) : super(version: 6);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    jornada,
    ubicacion,
    espacio,
    ubicacionParDecidido,
    campaniaCiudad,
    zona,
    zonaVertice,
    sesionUsuario,
    jornadaColportorIdx,
    ubicacionCiudadIdx,
    espacioUbicacionIdx,
    campaniaCiudadCiudadIdIdx,
    zonaCampaniaCiudadIdx,
    zonaVerticeZonaIdx,
  ];
  late final Shape0 jornada = Shape0(
    source: i0.VersionedTable(
      entityName: 'jornada',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'CHECK(total_visitas >= 0)',
        'CHECK(total_ventas >= 0)',
        'CHECK(fin IS NULL OR fin >= inicio)',
      ],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 ubicacion = Shape1(
    source: i0.VersionedTable(
      entityName: 'ubicacion',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'CHECK(tipo IN (\'CASA\', \'NEGOCIO\', \'EDIFICIO\'))',
        'CHECK(lat BETWEEN -90 AND 90)',
        'CHECK(lon BETWEEN -180 AND 180)',
      ],
      columns: [
        _column_0,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 espacio = Shape2(
    source: i0.VersionedTable(
      entityName: 'espacio',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 ubicacionParDecidido = Shape3(
    source: i0.VersionedTable(
      entityName: 'ubicacion_par_decidido',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(ubicacion_a_id, ubicacion_b_id)',
        'CHECK(decision IN (\'CONSERVAR_AMBOS\', \'IGNORAR\'))',
        'CHECK(ubicacion_a_id < ubicacion_b_id)',
      ],
      columns: [_column_24, _column_25, _column_26, _column_27],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 campaniaCiudad = Shape4(
    source: i0.VersionedTable(
      entityName: 'campania_ciudad',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_28,
        _column_18,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 zona = Shape5(
    source: i0.VersionedTable(
      entityName: 'zona',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'CHECK(tipo_forma IN (\'RADIAL\', \'ESQUINAS\'))',
        'CHECK(tipo_forma <> \'RADIAL\' OR(centro_lat IS NOT NULL AND centro_lon IS NOT NULL AND radio_m IS NOT NULL))',
        'CHECK(radio_m IS NULL OR radio_m BETWEEN 1 AND 3000)',
        'CHECK((centro_lat IS NULL OR centro_lat BETWEEN -90 AND 90)AND(centro_lon IS NULL OR centro_lon BETWEEN -180 AND 180))',
        'CHECK(color IS NULL OR color GLOB \'#[0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f]\')',
      ],
      columns: [
        _column_0,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
        _column_34,
        _column_35,
        _column_36,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 zonaVertice = Shape6(
    source: i0.VersionedTable(
      entityName: 'zona_vertice',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'CHECK(lat BETWEEN -90 AND 90)',
        'CHECK(lon BETWEEN -180 AND 180)',
      ],
      columns: [
        _column_0,
        _column_37,
        _column_38,
        _column_16,
        _column_17,
        _column_39,
        _column_40,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 sesionUsuario = Shape7(
    source: i0.VersionedTable(
      entityName: 'sesion_usuario',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(usuario_id)'],
      columns: [_column_41, _column_29],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index jornadaColportorIdx = i1.Index(
    'jornada_colportor_idx',
    'CREATE INDEX jornada_colportor_idx ON jornada (colportor_id, inicio)',
  );
  final i1.Index ubicacionCiudadIdx = i1.Index(
    'ubicacion_ciudad_idx',
    'CREATE INDEX ubicacion_ciudad_idx ON ubicacion (ciudad_id, lat)',
  );
  final i1.Index espacioUbicacionIdx = i1.Index(
    'espacio_ubicacion_idx',
    'CREATE INDEX espacio_ubicacion_idx ON espacio (ubicacion_id)',
  );
  final i1.Index campaniaCiudadCiudadIdIdx = i1.Index(
    'campania_ciudad_ciudad_id_idx',
    'CREATE INDEX campania_ciudad_ciudad_id_idx ON campania_ciudad (ciudad_id)',
  );
  final i1.Index zonaCampaniaCiudadIdx = i1.Index(
    'zona_campania_ciudad_idx',
    'CREATE INDEX zona_campania_ciudad_idx ON zona (campania_ciudad_id)',
  );
  final i1.Index zonaVerticeZonaIdx = i1.Index(
    'zona_vertice_zona_idx',
    'CREATE INDEX zona_vertice_zona_idx ON zona_vertice (zona_id, orden)',
  );
}

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get usuarioId =>
      columnsByName['usuario_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get nombre =>
      columnsByName['nombre']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_41(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'usuario_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

final class Schema7 extends i0.VersionedSchema {
  Schema7({required super.database}) : super(version: 7);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    jornada,
    ubicacion,
    espacio,
    ubicacionParDecidido,
    campaniaCiudad,
    zona,
    zonaVertice,
    sesionUsuario,
    auditLog,
    jornadaColportorIdx,
    ubicacionCiudadIdx,
    espacioUbicacionIdx,
    campaniaCiudadCiudadIdIdx,
    zonaCampaniaCiudadIdx,
    zonaVerticeZonaIdx,
    auditLogEventoUuidIdx,
  ];
  late final Shape0 jornada = Shape0(
    source: i0.VersionedTable(
      entityName: 'jornada',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'CHECK(total_visitas >= 0)',
        'CHECK(total_ventas >= 0)',
        'CHECK(fin IS NULL OR fin >= inicio)',
      ],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 ubicacion = Shape1(
    source: i0.VersionedTable(
      entityName: 'ubicacion',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'CHECK(tipo IN (\'CASA\', \'NEGOCIO\', \'EDIFICIO\'))',
        'CHECK(lat BETWEEN -90 AND 90)',
        'CHECK(lon BETWEEN -180 AND 180)',
      ],
      columns: [
        _column_0,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 espacio = Shape2(
    source: i0.VersionedTable(
      entityName: 'espacio',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 ubicacionParDecidido = Shape3(
    source: i0.VersionedTable(
      entityName: 'ubicacion_par_decidido',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(ubicacion_a_id, ubicacion_b_id)',
        'CHECK(decision IN (\'CONSERVAR_AMBOS\', \'IGNORAR\'))',
        'CHECK(ubicacion_a_id < ubicacion_b_id)',
      ],
      columns: [_column_24, _column_25, _column_26, _column_27],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 campaniaCiudad = Shape4(
    source: i0.VersionedTable(
      entityName: 'campania_ciudad',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_28,
        _column_18,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 zona = Shape5(
    source: i0.VersionedTable(
      entityName: 'zona',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'CHECK(tipo_forma IN (\'RADIAL\', \'ESQUINAS\'))',
        'CHECK(tipo_forma <> \'RADIAL\' OR(centro_lat IS NOT NULL AND centro_lon IS NOT NULL AND radio_m IS NOT NULL))',
        'CHECK(radio_m IS NULL OR radio_m BETWEEN 1 AND 3000)',
        'CHECK((centro_lat IS NULL OR centro_lat BETWEEN -90 AND 90)AND(centro_lon IS NULL OR centro_lon BETWEEN -180 AND 180))',
        'CHECK(color IS NULL OR color GLOB \'#[0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f]\')',
      ],
      columns: [
        _column_0,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
        _column_34,
        _column_35,
        _column_36,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 zonaVertice = Shape6(
    source: i0.VersionedTable(
      entityName: 'zona_vertice',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'CHECK(lat BETWEEN -90 AND 90)',
        'CHECK(lon BETWEEN -180 AND 180)',
      ],
      columns: [
        _column_0,
        _column_37,
        _column_38,
        _column_16,
        _column_17,
        _column_39,
        _column_40,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 sesionUsuario = Shape7(
    source: i0.VersionedTable(
      entityName: 'sesion_usuario',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(usuario_id)'],
      columns: [_column_41, _column_29],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 auditLog = Shape8(
    source: i0.VersionedTable(
      entityName: 'audit_log',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_42, _column_43, _column_44, _column_45, _column_46],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index jornadaColportorIdx = i1.Index(
    'jornada_colportor_idx',
    'CREATE INDEX jornada_colportor_idx ON jornada (colportor_id, inicio)',
  );
  final i1.Index ubicacionCiudadIdx = i1.Index(
    'ubicacion_ciudad_idx',
    'CREATE INDEX ubicacion_ciudad_idx ON ubicacion (ciudad_id, lat)',
  );
  final i1.Index espacioUbicacionIdx = i1.Index(
    'espacio_ubicacion_idx',
    'CREATE INDEX espacio_ubicacion_idx ON espacio (ubicacion_id)',
  );
  final i1.Index campaniaCiudadCiudadIdIdx = i1.Index(
    'campania_ciudad_ciudad_id_idx',
    'CREATE INDEX campania_ciudad_ciudad_id_idx ON campania_ciudad (ciudad_id)',
  );
  final i1.Index zonaCampaniaCiudadIdx = i1.Index(
    'zona_campania_ciudad_idx',
    'CREATE INDEX zona_campania_ciudad_idx ON zona (campania_ciudad_id)',
  );
  final i1.Index zonaVerticeZonaIdx = i1.Index(
    'zona_vertice_zona_idx',
    'CREATE INDEX zona_vertice_zona_idx ON zona_vertice (zona_id, orden)',
  );
  final i1.Index auditLogEventoUuidIdx = i1.Index(
    'audit_log_evento_uuid_idx',
    'CREATE INDEX audit_log_evento_uuid_idx ON audit_log (evento, uuid)',
  );
}

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get evento =>
      columnsByName['evento']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get uuid =>
      columnsByName['uuid']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get motivo =>
      columnsByName['motivo']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get creadoEn =>
      columnsByName['creado_en']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_42(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      hasAutoIncrement: true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL PRIMARY KEY AUTOINCREMENT',
    );
i1.GeneratedColumn<String> _column_43(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'evento',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_44(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'uuid',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_45(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'motivo',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_46(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'creado_en',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
  required Future<void> Function(i1.Migrator m, Schema5 schema) from4To5,
  required Future<void> Function(i1.Migrator m, Schema6 schema) from5To6,
  required Future<void> Function(i1.Migrator m, Schema7 schema) from6To7,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      case 2:
        final schema = Schema3(database: database);
        final migrator = i1.Migrator(database, schema);
        await from2To3(migrator, schema);
        return 3;
      case 3:
        final schema = Schema4(database: database);
        final migrator = i1.Migrator(database, schema);
        await from3To4(migrator, schema);
        return 4;
      case 4:
        final schema = Schema5(database: database);
        final migrator = i1.Migrator(database, schema);
        await from4To5(migrator, schema);
        return 5;
      case 5:
        final schema = Schema6(database: database);
        final migrator = i1.Migrator(database, schema);
        await from5To6(migrator, schema);
        return 6;
      case 6:
        final schema = Schema7(database: database);
        final migrator = i1.Migrator(database, schema);
        await from6To7(migrator, schema);
        return 7;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
  required Future<void> Function(i1.Migrator m, Schema5 schema) from4To5,
  required Future<void> Function(i1.Migrator m, Schema6 schema) from5To6,
  required Future<void> Function(i1.Migrator m, Schema7 schema) from6To7,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(
    from1To2: from1To2,
    from2To3: from2To3,
    from3To4: from3To4,
    from4To5: from4To5,
    from5To6: from5To6,
    from6To7: from6To7,
  ),
);
